"""
SumScale — Free Reminder & Alerting Service
===========================================
100% Free Notification & Scheduling System:
- Gmail SMTP for instant email alerts & reminders
- 1-Click Google Calendar event URL generator (Zero API keys / OAuth needed)
"""

import os
import logging
import smtplib
import urllib.parse
from datetime import datetime, timezone, timedelta
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Optional, List

from app.config import settings

logger = logging.getLogger("omniaid.reminder_service")


def create_google_calendar_link(
    title: str,
    details: str,
    start_dt: Optional[datetime] = None,
    duration_minutes: int = 30,
) -> str:
    """
    Generates a 100% FREE 1-click Google Calendar template URL.
    No OAuth or Google API credentials required.
    Opens directly in Google Calendar on web, Android, iOS, or desktop.
    """
    if start_dt is None:
        start_dt = datetime.now(timezone.utc) + timedelta(days=1)
    elif start_dt.tzinfo is None:
        start_dt = start_dt.replace(tzinfo=timezone.utc)

    end_dt = start_dt + timedelta(minutes=duration_minutes)

    # Format ISO string without hyphens or colons for Google Calendar URL (YYYYMMDDTHHMMSSZ)
    start_str = start_dt.strftime("%Y%m%dT%H%M%SZ")
    end_str = end_dt.strftime("%Y%m%dT%H%M%SZ")

    params = {
        "action": "TEMPLATE",
        "text": f"SumScale Reminder: {title}",
        "details": f"{details}\n\nGenerated by SumScale Multimodal AI Engine.",
        "dates": f"{start_str}/{end_str}",
    }

    return f"https://calendar.google.com/calendar/render?{urllib.parse.urlencode(params)}"


def send_free_email_alert(
    recipient_email: str,
    case_title: str,
    summary: str,
    checklist: Optional[List[str]] = None,
    google_calendar_url: Optional[str] = None,
) -> bool:
    """
    Sends a 100% free, beautifully formatted HTML case reminder/alert via Gmail SMTP.
    Includes case summary, remediation checklist, and 1-click Google Calendar button.
    """
    smtp_user = os.getenv("SMTP_USER") or getattr(settings, "SMTP_USER", "")
    smtp_password = os.getenv("SMTP_PASSWORD") or getattr(settings, "SMTP_PASSWORD", "")

    if not smtp_user or not smtp_password:
        logger.error("SMTP_USER / SMTP_PASSWORD not configured for free email alerts.")
        return False

    msg = MIMEMultipart()
    msg["From"] = f"SumScale Assistant <{smtp_user}>"
    msg["To"] = recipient_email
    msg["Subject"] = f"🔔 Reminder: SumScale Case Update - {case_title}"

    checklist_html = ""
    if checklist:
        checklist_items = "".join(f"<li style='margin-bottom: 6px;'>{item}</li>" for item in checklist)
        checklist_html = f"""
        <div style="background: #EDF6F9; border-left: 4px solid #006D77; padding: 14px; border-radius: 8px; margin: 18px 0;">
            <h4 style="margin: 0 0 8px; color: #006D77; font-size: 14px;">Key Recommended Actions:</h4>
            <ul style="margin: 0; padding-left: 20px; color: #333; font-size: 13px;">
                {checklist_items}
            </ul>
        </div>
        """

    cal_button_html = ""
    if google_calendar_url:
        cal_button_html = f"""
        <div style="text-align: center; margin: 24px 0;">
            <a href="{google_calendar_url}" target="_blank" style="background: linear-gradient(135deg, #006D77, #00B4D8); color: #ffffff; padding: 12px 24px; text-decoration: none; border-radius: 30px; font-weight: bold; font-size: 14px; display: inline-block; box-shadow: 0 4px 10px rgba(0,109,119,0.3);">
                📅 Add Reminder to Google Calendar
            </a>
        </div>
        """

    body = f"""
    <!DOCTYPE html>
    <html>
      <body style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 20px; background-color: #f4f7f6; color: #333;">
        <div style="max-width: 520px; margin: 0 auto; background: #ffffff; border: 1px solid #83C5BE; border-radius: 24px; padding: 32px; box-shadow: 0 4px 16px rgba(0,0,0,0.06);">
          <div style="display: flex; align-items: center; margin-bottom: 20px;">
            <span style="font-size: 24px; margin-right: 10px;">🔔</span>
            <h2 style="color: #006D77; margin: 0; font-size: 20px;">SumScale Case Reminder</h2>
          </div>
          
          <p style="font-size: 14px; color: #555; line-height: 1.5; margin-top: 0;">
            Here is your requested notification update for <strong>{case_title}</strong>:
          </p>

          <div style="background: #fafafa; border: 1px solid #eee; border-radius: 12px; padding: 16px; margin: 16px 0; font-size: 13px; color: #444; line-height: 1.6;">
            {summary}
          </div>

          {checklist_html}

          {cal_button_html}

          <hr style="border: none; border-top: 1px solid #eee; margin: 24px 0;" />
          <p style="font-size: 11px; color: #888; text-align: center; margin: 0;">
            © 2026 SumScale Multimodal AI Platform — Free Health &amp; Security Assistant
          </p>
        </div>
      </body>
    </html>
    """
    msg.attach(MIMEText(body, "html"))

    # Attempt 1: Port 587 (STARTTLS)
    try:
        with smtplib.SMTP("smtp.gmail.com", 587, timeout=10) as server:
            server.starttls()
            server.login(smtp_user, smtp_password)
            server.sendmail(smtp_user, recipient_email, msg.as_string())
        logger.info(f"✅ Free Email Alert delivered to {recipient_email} via Gmail SMTP")
        return True
    except Exception as e587:
        logger.warning(f"Port 587 email failed for {recipient_email}: {e587}. Trying SSL 465...")

    # Attempt 2: Port 465 (SSL)
    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465, timeout=10) as server:
            server.login(smtp_user, smtp_password)
            server.sendmail(smtp_user, recipient_email, msg.as_string())
        logger.info(f"✅ Free Email Alert delivered to {recipient_email} via Gmail SSL")
        return True
    except Exception as e465:
        logger.error(f"Failed to send email alert to {recipient_email}: {e465}")
        return False
